### ISSUE TITLE
Is this another abandoned Hugo theme?

### ISSUE THREAD

**Issue by pauby** [vjeantet/hugo-theme-docdock#151]
Is this theme still maintained? Issues and PR's seem to indicate not. I'm looking to add a documentation theme but I'm not interested in adding one that's been abandoned.

Anybody?

**Comment by Pilskalns** [comment]
Hi @pauby, @vjeantet 

I am using this at my workplace for internal docs as this was the best-suited/working when I looked around for Hugo documentation themes and don't see any reason to migrate away anytime soon.

Though for our production I am building from my fork, which usually lags behind a little. Just to keep things stable and no worry, every few months I update my fork in sync with this repro.

Also, I've committed to this theme before with serious improvements and am interested in keeping it in good shape.

I cannot promise to be active every week here but could make it more often to keep out the clutter.
**So, maybe @vjeantet is willing to elevate my permissions so that I can help to review PR's?**

**Comment by vjeantet** [comment]
Hello @Pilskalns 

I’m ok with this, I’ll do it tonight.

This theme is still maintained, I need to find more time to allocate.

**Comment by Pilskalns** [comment]
_ping @vjeantet -t_

**Comment by vjeantet** [comment]
64 bytes from @vjeantet: icmp_seq=2 ttl=54 time=8h

@Pilskalns push rights OK

**Comment by divinerites** [comment]
That is good news !!! Thanks @Pilskalns & @vjeantet .

We also are using this theme internally for all our documentation and improving it internally.
If you take over and keep it alive I will propose some (small) updates / correct bugs

Long live docdock :-)
