### ISSUE TITLE
Refactor main stylesheet

### ISSUE THREAD

**Issue by SiamKreative** [vjeantet/hugo-theme-docdock#45]
I am already customizing the theme by using a custom theme variant. While customizing the theme using theme variant, I realized that the CSS could be improved.

Here are the things I have noticed about the stylesheet `theme.css`

- Way too many `!important` rules (64 times). Here is [an example](https://github.com/vjeantet/hugo-theme-docdock/blob/master/static/css/theme.css#L88-L111). This is mainly due to how the stylesheet is organized / structured.
- Inconsistent indentation / formatting, making it hard to read.
- No CSS variables in main stylesheet. If the variables were defined in the main stylesheet, then the theme variants would be way easier to created...

If you want I can try to create a PR

**Comment by vjeantet** [comment]
Yes can can PR this.

I'm thinking about refactoring the HTML structure too.

I'll wait for your css PR to work on it

**Comment by W-Floyd** [comment]
I'm interested in this also, but I'm thinking of trying it in SASS/SCSS. Not promising anything (don't hold your breath), but would that be okay for a PR if I ever get anywhere?

**Comment by vjeantet** [comment]
I'm ok, @SiamKreative what do you think ? Will it conflicts with your current work ?

**Comment by SiamKreative** [comment]
I haven't had much time to work on this, so if @W-Floyd feels like having a go I think he should.

**Comment by W-Floyd** [comment]
Okay, cool, I'll see what I can do. Keep in mind, I'm not experienced in
sass, nor web development in general, so I'm only going to make cautious
changes.

On Sep 6, 2017 5:56 PM, "Julien Vernet" <notifications@github.com> wrote:

I haven't had much time to work on this, so if @W-Floyd
<https://github.com/w-floyd> feels like having a go I think he should.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/vjeantet/hugo-theme-docdock/issues/45#issuecomment-327405451>,
or mute the thread

**Comment by vjeantet** [comment]
W-Floyd scss PR merged
