### ISSUE TITLE
Issue with relative paths

### ISSUE THREAD

**Issue by arg0s** [vjeantet/hugo-theme-docdock#63]
<img width="721" alt="screen shot 2017-09-11 at 9 19 11 am" src="https://user-images.githubusercontent.com/927472/30257854-797f8d40-96d2-11e7-9f11-6c9b5d2d7659.png">

Does anyone else have trouble getting the example site to work with relative paths? (See attached).

I have the same problem on my main deployed site.

**Comment by arg0s** [comment]
Ignore this - the base URL was off.

**Comment by arg0s** [comment]
Oops, having this issue in the stock example site as well.  See how images are not getting loaded since the path to static is not getting pulled correctly and expects the top level. 
<img width="606" alt="screen shot 2017-09-11 at 9 45 17 am" src="https://user-images.githubusercontent.com/927472/30258333-1957a0b6-96d6-11e7-91b7-2c2626dd0b61.png">

**Comment by Pilskalns** [comment]
@arg0s can you provide command used to preview site? How do you preview site at all? Default Hugo server port is 1313, which tells you do something off.

If you try to build example site, you have to copy sample content from exampleSite to root of Hugo directory.

**Comment by arg0s** [comment]
@Pilskalns 
Things work fine during preview (when I run `hugo server` and it runs on 1313 like you've mentioned)
Things break when I build for publishing (by running just `hugo`).  After running `hugo` I then just ran a simple web server from the top of the Hugo folder using 
`python -m SimpleHTTPServer`
If you run it from the top level and then browse down to the example site, you'll see that the relative paths to stylesheets, etc are working fine. It's just the static folder that's expected at the root level.

**Comment by Pilskalns** [comment]
@arg0s
When using build result, you should be serving from `<hugo root>/public`, instead of `<hugo root>/themes/docdock/exampleSite/public`

**Comment by arg0s** [comment]
@Pilskalns Thanks for your response. Any reason why the relative bathing rules which work fine for the other assets don't work for static?

**Comment by Pilskalns** [comment]
@arg0s my english is not sure what you mean with _bathing_, but Hugo during build works following:
* All static files (css, img, pdf etc) from `<hugo>/themes/docdock/static/` and `<hugo>/static/` gets copied over to `<hugo>/public/` (which becomes your webroot for browsing).
* Everything from `<hugo>/content/` runs trough layouts and resulting `.html` files also gets copied over to `<hugo>/public/`. 

As you can see, everything is sent to `<hugo>/public/`, which you should serve with Python or any other web server. In normal way, you cannot access `<hugo>/themes/docDock/exampleSite/`, because it is outside `<hugo>/public/` and you must not. Example content is meant to be copied over to Hugo root when exploring theme and to see how theme works, what variables, custom shortcodes etc.

If you are trying to install Hugo in subdirectory like `mysupersite.com/docs/` rather than directly on `mysupersite.com/`, then you should set correct `baseURL` in Hugo configuration, which gets appended to URL functions inside Hugo. **OR** turn off full paths  with domain name in URL functions (don't remember variable name).

For more specifics please refer to https://gohugo.io/documentation/

**Comment by petzi53** [comment]
I am not sure but I believe I have a similar problem: I wanted to get rid of demo/tutorial folders "create-page" and "content-organisation". But this generates a bunch of errors:

`ERROR 2017/09/19 11:13:33 error processing shortcode "theme/shortcodes/relref.html" for page "_index.md": template: theme/shortcodes/relref.html:10:15: executing "theme/shortcodes/relref.html" at <relref .Page>: error calling relref: No page found with path or logical name "create-page/page-images.md".`

It seems to me - through trial and error, I am not very familiar with hugo - that at least 3 errors of the 10 are related to the file `page-images.md`.

I am still experimenting with your theme and have still not deployed it to netlify. I am using hugo 0.27.1 with [blogdown](https://bookdown.org/yihui/blogdown/) at a local page. 

BTW: I love your template! It has so much configurable features and functionality (shortcuts). Thanks! [Just another minor thing: bold text is not visible with your font. I had to change to the font of the learn theme.]

**Comment by Pilskalns** [comment]
Hi @petzi53 this is because _index.md page tries to reference children .md files you deleted (relative reference or **relref**.md shortcode).

**Comment by petzi53** [comment]
Thank you! And sorry: I misunderstood the error messages and looked at the wrong places (templates).

**Comment by Pilskalns** [comment]
@arg0s, @vjeantet I think this topic have exhausted itself. I suggest to be closed.

**Comment by vjeantet** [comment]
thanks @Pilskalns

**Comment by cuttalfish** [comment]
@Pilskalns, I cannot find in any of my _index.md files where these references are and I'm getting the same error... 

`ERROR 2018/05/14 19:59:08 error processing shortcode "theme/shortcodes/relref" for page "_index.md": template: theme/shortcodes/relref.html:12:15: executing "theme/shortcodes/relref" at <relref .Page>: error calling relref: No page found with path or logical name "shortcodes/expand.md".`

Do you know what the source is?

**Comment by cuttalfish** [comment]
I figured it out... the error was being thrown by the relref short-codes embedded in the _index.md files. I had deleted referenced pages within a given directory and left the _index.md as is for dummy content while I was testing it out. However this was throwing many errors. Below is an example of the Hugo short-code references that were in my _index.md files while I had actually deleted the "homepage.md" markdown page. 

`[customize homepage]({{%relref "homepage.md"%}}) `
