### ISSUE TITLE
baseURL in subdirectory causes 404 on clippy.svg

### ISSUE THREAD

**Issue by barthoda** [vjeantet/hugo-theme-docdock#83]
My site is configured with a baseURL in /docs/.

Whenever a code snippet is used, the CSS tries to fetch /images/clippy.svg. This causes a 404 because the actual URL is /docs/images/clippy.svg

**Comment by W-Floyd** [comment]
That might be my bad. The CSS doesn't actually reference it anymore, I believe I moved it into the `learn.js` file. Still doesn't discount the fact that it's not working for you, so I'll need to look into this...

**Comment by barthoda** [comment]
Yeah it is hardcoded in the learn.js to retrieve from /images/clippy.svg.

**Comment by W-Floyd** [comment]
Sorry for the delay, I'm pretty busy with school for the next month, but I
haven't forgotten this issue.

**Comment by barthoda** [comment]
No worries. Do you know why the clippy.svg references another CSS file?

**Comment by W-Floyd** [comment]
If I remember correctly, it was from me trying to make the svg change
colour to match the body text, but I ran into sizing issues. The solution
might just be to revert some of those edits, seeing as I didn't go with it
in the end.

On 11 Oct. 2017 5:11 am, "barthoda" <notifications@github.com> wrote:

No worries. Do you know why the clippy.svg references another CSS file?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vjeantet/hugo-theme-docdock/issues/83#issuecomment-335576997>,
or mute the thread

**Comment by vjeantet** [comment]
fixed

**Comment by W-Floyd** [comment]
@vjeantet thanks for getting that for me!

**Comment by vjeantet** [comment]
No pb
